# version: '3' # Deprecated use of version tag.
services:

  apt-cacher-ng:
    restart: always
    image: cr.pcfae.com/prplanit/apt-cacher-ng:2.7.4
    init: true
    ports:
    - "3142:3142"
    volumes:
    - /srv/docker/apt-cacher-ng:/var/cache/apt-cacher-ng
